### ISSUE TITLE
Slightly confusing syntax for querying documents

### ISSUE THREAD

**Issue by ahives** [phatboyg/Machete#1]
Currently I can query the document like this:

Parsed<HL7Entity> parsed = _parser.Parse(message);

var query = Query<HL7Entity>.Create(q =>
                from x in q.Select<MSHSegment>()
                select new {x.MessageType});

var result = query.Parse(parsed);

This is a bit unnatural from a developers perspective. Immediately I am thrown off by the different usages of the word Parse. From my perspective when I get a returned value from Query<HL7Entity>.Create I should be done. That statement should return my result. Right now the above code snippet reads:
1. Parse message
2. Create a query
3. Parse the query

I propose the following syntax,

var result = Query<HL7Entity>.Create(q =>
                from x in q.Select<MSHSegment>()
                select new {x.MessageType}).ExecuteAgainst(parsed);

or...

var query = Query<HL7Entity>.Create(q =>
                from x in q.Select<MSHSegment>()
                select new {x.MessageType});
var result = query.ExecuteAgainst(parsed);

This reads a little different,

1. Parse message
2. Create a query
3. Execute query against parsed message

Having a method called Parse hang off of the query can throw a developer off as to the purpose of staging the query to be executed against the parsed document.

**Comment by phatboyg** [comment]
Yeah, the trick is that Query.Create() just creates another parser (combinator). So it isn't really a query as it is a parser. I agree it's confusing, and I get the whole usage of Execute as a term. Just not sure how to apply it nicely.

**Comment by ahives** [comment]
This has totally grown on me. I like your suggestion. The syntax is succinct and it expressive as to what it does so that developers will understand examples clearly. Lets go with that.
