### ISSUE TITLE
Need a way to represent optional parsing

### ISSUE THREAD

**Issue by ahives** [phatboyg/Machete#11]
Currently, in the LINQ to Machete functionality we have a way to tell the parser to only select those segments of a particular type zero or more times.

`from obr in query.Select<OBR>().ZeroOrMore()`

Per the HL7 specification, there are times where we would want to only select a particular segment either zero or one times. In such a case we could syntax that looks like this,

`from obr in query.Select<OBR>().ZeroOrOne`

or

`from obr in query.Select<OBR>().Optionally()`

**Comment by phatboyg** [comment]
Isn't this was `.FirstOrDefault()` is meant to handle?

**Comment by phatboyg** [comment]
https://github.com/phatboyg/Machete/blob/master/src/Machete.HL7.Tests/Query_Specs.cs#L97

**Comment by ahives** [comment]
That might be confusing to devs because of the LINQ construct with the same name. I just can imagine someone getting confused rather easily with the following syntax:

`var result = parsed.Query(q => { from msh in q.Select<MSH>()
from evn in q.Select<EVN>()
from nte in q.Select<NTE>().FirstOrDefault()`

...and then in another part of their code they are using the LINQ version for a IEnumerable. So, the above syntax for extracting an NTE reads as follows:

"Select the first NTE segment or return the default"

Instead, I'd like it to read as follows:

"Select a single NTE segment if one exists"

I think the above statement can be refined to look like this,

`from nte in q.Select<NTE>().FirstOrNone()`

I think developers do understand what Default means in the context of LINQ but I'd also want them to understand that the current FirstOrDefault method is encapsulating a HL7 construct for saying a particular segment is optional. I can see an argument for FirstOrDefault because it is familiar to developers who have used LINQ before. However, I can also see an argument for FirstOrNone for developers who know the HL7 specification. Personally, I like FirstOrNone because it does not lend itself to the idea that I am given the ability to specify a "default" value like we are able to do with our ValueOrDefault extension method.

**Comment by phatboyg** [comment]
Yeah, I see the confusion.

So how about just adding:

`.Optional()`

**Comment by ahives** [comment]
Sounds good, but I prefer:

`.Optionally()`

...as in, select the specified segment optionally.

**Comment by phatboyg** [comment]
Changed to `Optional`

Added `FirstOrDefault` for a series parser.
Added `SingleOrDefault` for a series parser.
