### ISSUE TITLE
HL7Entity causing naming collisions

### ISSUE THREAD

**Issue by ahives** [phatboyg/Machete#13]
There is a naming collision for the HL7Entity interface that is causing problems with HL7Entity. This interface can be found both in Machete.HL7 and Machete.HL7Schema. Why is Machete.HL7Schema.HL7Entity needed when the project Machete.HL7Schema already references Machete.HL7 where it lives? Seems like a problem with code gen.

**Comment by phatboyg** [comment]
It's within the namespace, but I can see how it might cause confusion. Suggestions? Rename it to HL7V26Entity?

**Comment by ahives** [comment]
Why do I need it in both places when Machete.HL7Schema references Machete.HL7 anyway? I think that might be confusion on my part @phatboyg. When generating the schema I realize that it might need to be there for compilation but why not simply configure generator to reference Machete.HL7 instead?

**Comment by phatboyg** [comment]
Because the separate base ensures that people don't screw up and use V26 and V25 in the same parser.

**Comment by ahives** [comment]
So, my assumption is that we want to have a base for each schema version. I would suggest that they be specific to that version then as you suggested. HL726Entity or something similar. It should be derived from HL7Entity though.

One thing we have been talking about for years is the ability to transform from one version to another. For example, a developer may be using the HL7 2.5 spec but the message was sent to their system with the HL7 2.6 spec. In such a case, it will matter a lot to have common base classes. At the same time we don't want to make it easy to allows developers to make silly mistakes.
