### ISSUE TITLE
Words Structure and Layout are confusing

### ISSUE THREAD

**Issue by ahives** [phatboyg/Machete#16]
Instead of Layout about something like DocumentSection instead. The reason is because layout is definition of a section of a document. Also, instead Structure what about something like Document. I think the words Layout and Structure don't really capture the meaning and can lead to confusion.

**Comment by phatboyg** [comment]
Those _previous_ terms don't sit well with me at all, technically they aren't even documents.

I actually like the `Layout` term, structure doesn't sit well with me though. I'm avoiding the document terminology entirely.

**Comment by ahives** [comment]
@phatboyg just want to get inside your head a bit on why you like Layout and don't like Document.

**Comment by phatboyg** [comment]
Because document doesn't convey any information, at all. It's saying "here's a thing." It's like service or object, it means nothing. It could be a string.

Layout indicates that entities are organized in a specific way, versus a random collection.

In the HL7 specification, it's actually called a static definition isn't it? Maybe it isn't layout, maybe it's Group? I'm not sure yet. But I didn't like Template.

**Comment by ahives** [comment]
Yeah in HL7 its referred to as a Group.

But here is the rub, we want to be able to transform data between different specifications and it all makes sense. Good example is that I might want to transform a ORU into a CDA or vice-versa. In such a case, I ask myself if I'f want to deal with a common set of objects or specification specific objects.

With this in mind, Layout does sound like something common and it makes sense. So, as for Structure, lets take a step back and define what problem we are trying to solve. A structure is something that encapsulates layouts. In the case of HL7, a structure is made up of both segments and layouts. In HL7 it would be referred to as a _message_. In CDA it would be referred to as a _document_. However, we need something that is more generic to any spec like X12 or CSV, etc.

Below are a few suggestions of what we can use instead of structure:

Corpus
Content
Summary

Content is generic and does not suggest order so, although generic, it is my least favorite. Also, it might be too generic. Now, Corpus and Summary suggests order just like Structure, which is exactly what makes Layout makes such a good choice. However, what is also good about Corpus is when you say something like, "Query the Corpus"

**Comment by phatboyg** [comment]
Well, structure came from "data structure", whereas layout came from entity layout. The entire thing is essentially a data model for in this case, an HL7 message.

I suppose, technically, the layouts are just part of the schema, since it defines the data model.

**Comment by ahives** [comment]
Well, the schema can have Layouts. Layouts are explicitly ordered schemas. Maybe instead of Structure, maybe it should be just as you said, Schema. In which case, you would have an implicit schema and a explicit schema called a Layout. The implicit schema would possibly include zero or more explicit schemas. In the case of HL7 it could include just an ordered list of Segment<T>. Explicit schemas would be a ordered list of Segment<T> as well with the added ability to control how the Layout itself appears as part of what I am calling the Schema. You do not have such control over implicit schemas since they are the embodiment of the entire data structure.

**Comment by phatboyg** [comment]
So layouts are now part of Schema. Suspect we can close this.

**Comment by ahives** [comment]
Fixed.
