### ISSUE TITLE
Syntax for defining required segments within layout needs rethink

### ISSUE THREAD

**Issue by ahives** [phatboyg/Machete#27]
This is a bit weird syntax when defining a segment within a layout as required. Below is the current syntax...

Segment(x => x.ORC, 0, x => x.Required = true);

I propose we change this to...

Segment(x => x.ORC, 0, x => x.IsRequired());

...that way by default it is not required. Another, even more simple, syntax would be to simply this parameter with a boolean like so,

Segment(x => x.ORC, 0, true);

...this would be an optional parameter set to false by default.

**Comment by phatboyg** [comment]
There are extension methods to do this type of stuff, they just aren't used by the generator for the HL7 schema.

See:
https://github.com/phatboyg/Machete/blob/master/src/Machete.HL7.Tests/Segments/EVNSegmentMap.cs#L13

**Comment by ahives** [comment]
This is good but I still think having it as a settable property is different from the established pattern of things being immutable. I don't want to make it easy for developers to mess up definitions, which is why I prefer a method that internally sets the field/property.

**Comment by phatboyg** [comment]
It makes no difference, and property setters are faster. It's what MT uses almost exclusively now.

**Comment by ahives** [comment]
Got it. Perhaps the compromise is to change the name to IsRequired. Required = true just sounds weird to me. IsRequired = true speaks to the developer. Its like asking the developer is the ORC segment required? Yes.

**Comment by phatboyg** [comment]
I tweaked this a little in cc98ccf

**Comment by ahives** [comment]
Done. Closing.
