### ISSUE TITLE
Layout parsing inconsistent with LINQ parser

### ISSUE THREAD

**Issue by ahives** [phatboyg/Machete#28]
When I call Structure.TryGetLayout(out layout) to return a layout it returns

         ILayoutParserFactory<T, HL7Entity>

...where T is the layout. For starters I wouldn't call this ILayoutParserFactory and I will explain why a little later after I give more context.

Consider the following syntax for querying a parsed message...

            ParseResult<HL7Entity> parse = Parser.Parse(message);
            var result = parse.Query(q =>
            {
                var obxQuery = from obx in q.Select<OBX>()
                    from nte in q.Select<NTE>().ZeroOrMore()
                    select new
                    {
                        OBX = obx,
                        NTE = nte
                    };

                var obrQuery = from obr in q.Select<OBR>()
                    from dg1 in q.Select<DG1>().Optional()
                    from obx in obxQuery.Optional()
                    select new
                    {
                        OBR = obr,
                        DG1 = dg1,
                        OBX = obx
                    };

                var testQuery = from orc in q.Select<ORC>()
                    from obr in obrQuery.ZeroOrMore()
                    select new
                    {
                        ORC = orc,
                        OBR = obr
                    };

                return from msh in q.Select<MSH>()
                    from nte in q.Select<NTE>().ZeroOrMore()
                    from skip in q.Except<HL7Segment, ORC>().ZeroOrMore()
                    from tests in testQuery.ZeroOrMore()
                    select new
                    {
                        MSH = msh,
                        Notes = nte,
                        Tests = tests
                    };
            });

...as you can see I parse the message then query it. However, layouts I have to do the following...

     EntityResult<HL7Entity> entityResult = Parser.Parse(message);
     ILayoutParserFactory<SomeLayout, HL7Entity> layout;
     Structure.TryGetLayout(out layout)
     Parser<HL7Entity, SomeLayout> query = entityResult.CreateQuery(q => layout.CreateParser(LayoutParserOptions.None, q));
     Result<Cursor<HL7Entity>, SomeLayout> result = entityResult.Query(query);

When compared, using layouts takes at least 4 steps to do what I can with LINQ in 2. Perhaps we can combine the first two steps of parsing out a layout into something like this...

     LayoutResult<SomeLayout, HL7Entity> parse = Structure.Parse(message)

This would be more natural syntax to what the developer has now been used to with the LINQ parser, which by this time they'd probably be well versed.

**Comment by phatboyg** [comment]
Things to consider:

    1. Layouts will be slightly faster than writing an ad hoc LINQ query, since they are compiled from the layout definition (which is a map, similar to the entity maps).
    2. Layouts are included for the default message types, such as ORU, etc. so that you don't need to write the query at all (reducing the chance for errors).

That said, I'm all for making the syntax easier to use. Just recognize that we should be conflating the concepts of parse, query, layout, etc. into a single static method.

Perhaps something along the lines of:

    IStructure<HL7Layout> structure = ...;
    LayoutResult<SomeLayout> result = structure.QueryLayout<SomeLayout>(entityResult);

I tried to pull layouts into the Schema, but it created a ton of issue with generic types that broke discovery so I discarded the branch.

Thoughts?

**Comment by ahives** [comment]
So, I think at a basic level what I was referring to is the fact that Layouts are sort of predefined queries so I like the. following syntax,

LayoutResult<SomeLayout> result = structure.Query<SomeLayout>(entityResult);

This way we can have extension methods later to format, transform, and even make it accessible to LINQ to Schema. I like this syntax but I'd like to change QueryLayout to just Query though. Other than that I like this.

**Comment by phatboyg** [comment]
Check it out.

**Comment by ahives** [comment]
Love it. Closing.
