### ISSUE TITLE
Create test helper package

### ISSUE THREAD

**Issue by ahives** [phatboyg/Machete#5]
Create a package for helping developers test the applications they build using Machete. Some things that are immediate needs are as follows:

- [ ] Setting up the parser
- [ ] Formatting HL7 messages for comparisons
- [ ] Comparing messages/documents
- [ ] Reading/loading messages/documents

**Comment by phatboyg** [comment]
The approach for this should be similar to the approach taking for MassTransit. A testing namespace that makes it unit test framework agnostic, but allows for the easy setup of tests.

**Comment by ahives** [comment]
That is what I had in mind. Question though, would that be a separate project/package with a testing namespace? I am thinking that it would be but wanted to confirm.

**Comment by phatboyg** [comment]
Same assembly. Just a namespace. For the core testing bits, not any sample data or anything. 

____
Chris Patterson

**Comment by ahives** [comment]
So, I am thinking the right place to put it is in the Machete project. We can call it something like Machete.Testing

**Comment by phatboyg** [comment]
That's essentially what I did with MT: 

https://github.com/MassTransit/MassTransit/tree/develop/src/MassTransit/Testing

Makes it simple to setup an in-memory bus for testing all aspects of MT, but could have a similar approach for Machete.

https://github.com/MassTransit/MassTransit/blob/develop/src/MassTransit.Tests/Testing/ConsumerTest_Specs.cs#L30

**Comment by ahives** [comment]
We have the infrastructure for this setup now. Closing.
