### ISSUE TITLE
Handling of "Not Used" Elements

### ISSUE THREAD

**Issue by nycbauer** [phatboyg/Machete#55]
I'm trying to parse an X12 835 document, and the NM1 Segment has space for "Name Prefix" - NM106, which is labeled as "Not Used" in the documentation, however, I see that in your code you are ignoring this field.

For reference sake, I am getting my information from here: https://reviewer.x12.org/x322publicreviewweb
Then navigating to 2.4 \ Table 2 - Detail \ Loop 2100 - Claim Payment Information \ NM1 - Patient Name.
And I see in your code: Generated\V5010\Segments\Maps\NM1Map.cs - Line 20 sets position 6 to Name Suffix instead of Name Prefix.

Thank you!

**Comment by ahives** [comment]
Good catch. The fix is to increment the index for suffix to 7, qualifier to 8, and code to 9. Fix will be in need release.

**Comment by ahives** [comment]
fixed in release 1.0.236-develop

**Comment by ahives** [comment]
@nycbauer is this still an issue?

**Comment by nycbauer** [comment]
Nope, thank you!
