### ISSUE TITLE
Create a way to register necessary components to use within applications

### ISSUE THREAD

**Issue by ahives** [phatboyg/Machete#6]
Need a means to pull in artifacts to ease the use of Machete. Without this developers would have to register components on their own. Out of the box Machete should have Autofac support for the following things:

- [ ] Registering each parser type (e.g. layout, text, LINQ, etc.)
- [ ] Registering each schema
- [ ] Registering each transformer
- [ ] Registering each validator

Other IoCs can be added as we move along but Autofac currently has the biggest market share. Of course, people might not want to register their components using any IoC so for those folks you still have option of not using. I think it might make sense to put this in the Machete.* project under the folder Integration. For instance, Machete.HL7 would have one specific for HL7. There would be an interface in the Machete project though and the specific implementations would live where the subsequent schemas live.

**Comment by phatboyg** [comment]
Need to think about this more, so we can have a container for the parser, schema, translators, etc.

**Comment by ahives** [comment]
Added support for both Microsoft DI and Autofac. This will introduce new packages. To be in next release.
