### ISSUE TITLE
Handling unknown segments

### ISSUE THREAD

**Issue by ahives** [phatboyg/Machete#9]
Sometimes there will be segments defined by the source system that need to be rolled up into a LINQ to HL7 query. In such a case we need a way to select unknown segments.

I might want to query all the unknown segments skipping over all others. Here is a possible code fragment on how that query might look,

`from unknown in query.Select<HL7Segment>().Where(x => x.SegmentId.HasValue && x.SegmentId.Value != "ORC")`

**Comment by phatboyg** [comment]
Pretty sure this works given your samples.

**Comment by ahives** [comment]
Yeah, this looks something like,

from unknown q.Except<HL7Segment, ORC>()

I think we just don't have a test for this specific scenario. I will add one.
